spring.application.name=aserp

# DataSource - Neon PostgreSQL
spring.datasource.url=${NEON_DB_URL}
spring.datasource.username=neondb_owner
spring.datasource.password=npg_iAjv8OalW9Rc
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration